### ISSUE TITLE
libpng 1.5 Needs to update to libpng 1.6 version. (SITEGROUND SERVER)

### ISSUE THREAD

**Issue by niravrathod** [rvanlaak/wkhtmltopdf-amd64-centos7#2]
Hello guys,

I am trying to add wkhtmltopdf in my siteground shared hosted server, but the issue is they have installed the latest version of binary libpng 1.6 and they don't downgrade to 1.5, so my request is to please update the binary to libpng 1.6

Thanks,
Nirav Rathod.

**Comment by rvanlaak** [comment]
This repository does simply provide the binary in a way so Composer can install it. There is no way for me to update the binary itself. You can approach https://wkhtmltopdf.org/ to do so.

Meaning, for now I'm going to close this issue.
